//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatyamSirWork1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_user
    {
        public int id { get; set; }
        [Required]
        [Display(Name ="UserName")]
        public string UserName { get; set; }
        [Required]
        [Display(Name = "Password")]
        public string Pass_word { get; set; }
    }
}
